# Generated by Django 4.2.4 on 2023-09-07 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 2, 42, 58, 450977, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'NewsLitter',
                'verbose_name_plural': 'NewsLitter',
            },
        ),
    ]
