# Generated by Django 4.2.4 on 2023-12-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_newslitter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
