# Generated by Django 4.2.4 on 2023-08-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertybook_children_alter_propertybook_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icons',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
