# Generated by Django 4.2.4 on 2023-11-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyreview',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertyreview',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='feedback',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='rate',
            field=models.FloatField(),
        ),
    ]
