# Generated by Django 4.2.4 on 2023-12-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_rename_auther_propertyreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
